rpmbuild:
  build: .
  volumes:
    - .:/root:ro
    - rpmbuild:/root/rpmbuild
  environment:
    SOURCE_URL: http://github.com/LemonBoy/bar/tarball/2e8ac2c
  working_dir: /root
  command:
    - bash
    - -c
    - |
      #!/bin/bash
      mkdir -p rpmbuild/{SOURCES,SPECS}
      cp lemonbar.spec rpmbuild/SPECS
      if [ ! -f rpmbuild/SOURCES/LemonBoy-bar-2e8ac2c.tar.gz ]
      then
        curl -vfL "$SOURCE_URL" > rpmbuild/SOURCES/LemonBoy-bar-2e8ac2c.tar.gz
      fi
      rpmbuild -ba rpmbuild/SPECS/lemonbar.spec
