rpmbuild:
  build: .
  volumes:
    - .:/root:ro
    - rpmbuild:/root/rpmbuild
  environment:
    SOURCE_URL: http://github.com/PH111P/bar/tarball/a8d8e9d
  working_dir: /root
  command:
    - bash
    - -c
    - |
      #!/bin/bash
      mkdir -p rpmbuild/{SOURCES,SPECS}
      cp lemonbar-xft.spec rpmbuild/SPECS
      if [ ! -f rpmbuild/SOURCES/PH111P-bar-a8d8e9d.tar.gz ]
      then
        curl -vfL "$SOURCE_URL" > rpmbuild/SOURCES/PH111P-bar-a8d8e9d.tar.gz
      fi
      rpmbuild -ba rpmbuild/SPECS/lemonbar-xft.spec
